name: hijri_date_time
description: "A Dart package for working with Hijri calendar dates and performing date conversions."
version: 1.0.0
repository: https://github.com/paighaam/hijri-date-time
homepage: https://github.com/paighaam/hijri-date-time
documentation: https://github.com/paighaam/hijri-date-time/wiki

topics:
  - hijri
  - islamic-calendar
  - islamic
  - calendar
  - date

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
